### ISSUE TITLE
Provide an RSS feed + Icon for the website

### ISSUE THREAD

**Issue by ghost** [Vanilla-OS/website#127]
An RSS Feed plus an icon displaying it on the website would be great

**Comment by vendillah** [comment]
Related to issue #15. I actually came to open a new issue myself for the missing RSS myself as well, because it's a few months since the redesign that made it disappear and so far, we still don't know whether it was removed intentionally or merely temporarily.

Also, I find it suspicious that [the first two articles](https://vanillaos.org/blog) are both on the fifth of July, while I thought all this time there was only one article that day. I may have simply never noticed it, or it's a copy-paste error and the latter is actually of a more recent date (which is very likely, since it's referencing GUADEC, which occurs in August).

**Comment by GabsEdits** [comment]
An RSS Feed could be provided using [`feed`](http://npmjs.com/package/feed), and the articles can be taken right from the `articles/` folder.

**Comment by MMachado05** [comment]
I second this! The blog is getting updated a lot more frequently now, and I'd much prefer an RSS feed over cluttering my inbox with yet another newsletter my brain will automatically skim over. 😔

**Comment by Burrito78** [comment]
I couldn't believe that such a nice project didn't already have an RSS feed. Please support this, everything else is way too overwhelming for me just to keep up to date.

**Comment by vendillah** [comment]
The website used to have one at [https://vanillaos.org/feed.xml](https://vanillaos.org/feed.xml) and the change seems very intentional. It was dropped about [a year ago](https://github.com/Vanilla-OS/website/issues/15#issuecomment-1656875647) after moving to another framework/website and replaced by the "Newsletter". Personally, I don't want my news in my inbox -- I get enough already -- and neither do I want to provide an email address for that, even though aliases exist.

**Comment by MMachado05** [comment]
@vendillah Exactly; I use email for exactly that - electronic mail. To communicate with others. As much as I love the VanillaOS project, I don't want to clutter my inbox with something completely unrelated to my important communications...

**Comment by GabsEdits** [comment]
The [pull request](https://github.com/Vanilla-OS/website/pull/228) has been merged and the RSS/Atom Feed is now provided once again on the URL as last time: https://vanillaos.org/feed.xml

**Comment by kbdharun** [comment]
**Update:** The RSS feed is available now (thanks to @GabsEdits) and you can add https://vanillaos.org/feed.xml to the RSS reader of your choice.

Currently, it's listed in the website's footer, ~~for better discoverability I have suggested adding an RSS Feed icon to the header.~~ seems like it is listed in the blog section as well as inside articles so IG its fine.

![image](https://github.com/user-attachments/assets/71196f4d-ccd9-4675-8f8b-2665fbedf4ab)
