### ISSUE TITLE
bad contrast on help page in dark mode

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/website#225]
At the bottom of this page:
https://vanillaos.org/help/faq

there is a purple box with purple text and the contrast is very poor.

**Comment by sagbdev** [comment]
![Screenshot from 2024-07-28 21-26-25](https://github.com/user-attachments/assets/b515a36f-2fbd-458e-b57a-48e10eee89ab)
![Screenshot from 2024-07-28 21-26-49](https://github.com/user-attachments/assets/59f38fa8-09f7-4668-8013-a61ed2d740c5)

I think I fixed it, here's my [fork with the changes](https://github.com/santiago-webdev/website), I don't know what to do after that.

**Comment by sagbdev** [comment]
I'll have to take a little bit more time to understand how to fix it, because the hover states are broken for the dark theme (both for the purple and green cards), the easy fix would be keeping the defaults of the light theme and get it over, but I don't know what the creator of the design system had in mind when it created it.
